name = "app"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
temporary = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.3.2 and < 3.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
lustre = ">= 5.4.0 and < 6.0.0"
frontmatter = ">= 1.0.1 and < 2.0.0"
tom = ">= 2.0.0 and < 3.0.0"
mork = ">= 1.11.0 and < 2.0.0"

# [tools.lustre.build]
# minify = true
# outdir = "./dist"

# [tools.lustre.dev]
# host = "0.0.0.0"
# port = 8080

# [tools.lustre.html]
# title = "wiskiy"
# links = [
#   { rel = "preload", href = "/images/me.jpg", as = "image" },

#   { rel = "preload", href = "/icons/github.svg", as = "image" },
#   { rel = "preload", href = "/icons/discord.svg", as = "image" },
#   { rel = "preload", href = "/icons/telegram.svg", as = "image" },
#   { rel = "preload", href = "/icons/email.svg", as = "image" },

#   { rel = "icon", href = "/favicon.ico" },
#   { rel = "alternate", type = "application/rss+xml", title = "wiskiy's blog", href = "/feed.xml" },
# ]
# scripts = [
#   { src = "/highlight.min.js" },
#   # { src = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/languages/diff.min.js" },
#   { src = "/gleam.min.js" },
#   # { content = "hljs.highlightAll();" },
# ]
