name: Deploy static to Pages

on:
  push:
    branches:
      - gleamy
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.14.0"
          rebar3-version: "3"

      - name: Install dependencies
        run: gleam deps download

      - name: Build
        run: gleam run -m build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
